version: '3.4'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  love-station-api:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    image: love-station-api-prod:latest
    container_name: love-station-api-prod
    restart: always
    environment:
      - SPRING_REDIS_HOST=redis
      - TZ=Asia/Taipei
    volumes:
      - ./storage:/app/storage
    depends_on:
      - redis
    ports:
      - 8080:8080