version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'LoveStation123!'
      TZ: 'Asia/Taipei'
    ports:
      - 1433:1433

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379